POST http://127.0.0.1:8324/message
Content-Type: application/json
access_token: 12345678

{
    "message": "okay then one. just do random",
    "thread_id": "thread_V6DmBTg9xmmldnHJBBkOFbyE"
}

###

POST http://127.0.0.1:8324/thread
Content-Type: application/json
access_token: 12345678

###
POST https://1007-94-143-189-243.ngrok-free.app/thread/
Content-Type: application/json
access_token: 12345678

